# Generated by Django 5.0.2 on 2024-02-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='room',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
    ]
